### ISSUE TITLE
Error: login failed!

### ISSUE THREAD

**Issue by Evg33** [basiliocat/mos.ru#11]
Error: login failed!
Потому как они видимо убрали https://oauth20.mos.ru/sps/j_security_check
Теперь по ней 404 - Not Found.
Возможно https://oauth20.mos.ru/sps/login/methods/password теперь.

**Comment by evgenyvolferts** [comment]
https://oauth20.mos.ru/sps/j_security_check перенаправляет на https://oauth20.mos.ru/sps/wasauth
У меня историю показаний скрипт забирает без проблем

**Comment by Evg33** [comment]
Да, всё работает теперь. Видимо опять были техработы на мосру.

**Comment by EvelRus** [comment]
А у меня не работает ( Опять что-то поменяли?

**Comment by evgenyvolferts** [comment]
> А у меня не работает ( Опять что-то поменяли?

Поменяли еще в декабре. Обновление у меня в форке.

**Comment by Spirituss** [comment]
@evgenyvolferts 
> > А у меня не работает ( Опять что-то поменяли?
> 
> Поменяли еще в декабре. Обновление у меня в форке.

А Мосэнергосбыт работает в твоем форке? У меня get не работает, ничего не возвращает.

**Comment by evgenyvolferts** [comment]
> А Мосэнергосбыт работает в твоем форке? У меня get не работает, ничего не возвращает.

Я, если честно, на него забил. Для передачи данных счетчиков воды использую свою реализацию на php, а показания электросчетчика ходят снимают вручную раз в месяц сотрудники мосэнергосбыта.
