### ISSUE TITLE
Вытащить PGU в отдельный API?

### ISSUE THREAD

**Issue by grimich** [basiliocat/mos.ru#5]
Привет
А не думал вытащить все общение с PGU в отдельный API? 
Сделать что-то типа открытого API по работе с PGU?

**Comment by basiliocat** [comment]
Bash как-то плохо подходит для API. Да и не просматривается там на mos.ru общих принципов - каждую услугу надо автоматизировать отдельно. Пока это ad-hoc (то есть набор костылей), который к тому же часто ломается по причине изменений на серверной стороне
